version: '3.8'
services:
  postgres:
    image: postgres
    container_name: marcinho-excursoes-backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: embarqueja
    restart: always
    ports:
      - "5432:5432"