"""inital migrations

Revision ID: f3271582ec93
Revises: 
Create Date: 2026-03-18 15:00:45.175965
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f3271582ec93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='public'
    )
    op.create_table('embarque',
    sa.Column('local_embarque', sa.String(), nullable=True),
    sa.Column('horario_embarque', sa.TIME(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('excursao',
    sa.Column('hotel', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('destino', sa.String(), nullable=True),
    sa.Column('data_saida', sa.DATE(), nullable=True),
    sa.Column('data_retorno', sa.DATE(), nullable=True),
    sa.Column('status_viagem', sa.Enum('disponivel', 'cancelada', name='statusviagem'), nullable=True),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('onibus',
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('total_assentos', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('url_imagem', sa.Text(), nullable=True),
    sa.Column('logo_sidebar', sa.Text(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('enderecos',
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['public.clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    schema='public'
    )
    op.create_table('excursao_embarque',
    sa.Column('excusao_id', sa.UUID(), nullable=False),
    sa.Column('embarque_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['embarque_id'], ['public.embarque.id'], ),
    sa.ForeignKeyConstraint(['excusao_id'], ['public.excursao.id'], ),
    sa.PrimaryKeyConstraint('excusao_id', 'embarque_id'),
    schema='public'
    )
    op.create_table('excursao_onibus',
    sa.Column('onibus_id', sa.UUID(), nullable=True),
    sa.Column('excusao_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['excusao_id'], ['public.excursao.id'], ),
    sa.ForeignKeyConstraint(['onibus_id'], ['public.onibus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('reservas',
    sa.Column('status_assento', sa.Enum('confirmado', 'pendente', 'cancelado', name='statusassento'), nullable=True),
    sa.Column('numero_assento', sa.Integer(), nullable=True),
    sa.Column('excursao_onibus_id', sa.UUID(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('valor_pago', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['public.clientes.id'], ),
    sa.ForeignKeyConstraint(['excursao_onibus_id'], ['public.excursao_onibus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas', schema='public')
    op.drop_table('excursao_onibus', schema='public')
    op.drop_table('excursao_embarque', schema='public')
    op.drop_table('enderecos', schema='public')
    op.drop_table('users', schema='public')
    op.drop_table('onibus', schema='public')
    op.drop_table('excursao', schema='public')
    op.drop_table('embarque', schema='public')
    op.drop_table('clientes', schema='public')
    # ### end Alembic commands ###
